---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  playbook: auth-playbook.yml
  require_ruby_for_busser: true

verifier:
  ruby_bindir: '/usr/bin'

platforms:
  - name: centos-6.7

suites:
  - name: RP1
    provisioner:
      hosts: RP
  - name: SSO1
    provisioner:
      hosts: SSO
  - name: LDAP1
    provisioner:
      hosts: LDAP
