# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box_url = "bento/centos-6.7"

  config.vm.define :'RP1-centos-67' do |proxy|
  end

  config.vm.define :'SSO1-centos-67' do |proxy|
  end

  config.vm.define :'LDAP1-centos-67' do |proxy|
  end
end
